### Transformer-TTS requried configuration
wav_directory: ''
metadata_path: ''
log_directory: ''
train_data_directory: ''
data_config: 'TransformerTTS/config/data_config_est.yaml'
aligner_config: 'TransformerTTS/config/aligner_config.yaml'
tts_config: 'TransformerTTS/config/tts_config_est.yaml'
data_name: ''

service: tts
workers:
  tonis_merlin:
    parameters:
      config_path: config/config.yaml
      checkpoint_path: models/tts/albert
      vocoder_path: models/hifigan/vctk
    routes:
      - tonis_merlin